name: CI

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'
    - 'feature/**'

jobs:

  ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run tests
        run: make ci
