name: CI

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'
    - 'feature/**'

jobs:

  ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - name: Determine Go cache paths
        id: golang-path
        run: |
          echo "build=$(go env GOCACHE)" >>"$GITHUB_OUTPUT"
          echo "module=$(go env GOMODCACHE)" >>"$GITHUB_OUTPUT"
        shell: bash

      - name: Setup Go cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.golang-path.outputs.build }}
            ${{ steps.golang-path.outputs.module }}
          key: ${{ runner.os }}-golang
          restore-keys: |
            ${{ runner.os }}-golang

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run tests
        run: make ci
